gerance:
    resource: "@GeranceBundle/Controller/"
    type:     annotation
    prefix:   /

user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /

admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /

front:
    resource: "@FrontBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"

# Route de connexion au FrontOffice
fos_user_security_login:
    path: /login
    defaults: { _controller: FOSUserBundle:Security:login }

# Route de vérification de connexion au FrontOffice
fos_user_security_check:
    path: /check
    defaults: { _controller: FOSUserBundle:Security:check }
    requirements:
        _method: POST

# Route de déconnexion du FrontOffice
fos_user_security_logout:
    path: /logout
    defaults: { _controller: FOSUserBundle:Security:logout }

# Route de connexion au Backoffice
admin_security_login:
    path:  /admin/login
    defaults: { _controller: FOSUserBundle:Security:login }

# Route de vérification de connexion au Backoffice
admin_security_check:
    path:  /admin/check
    defaults: { _controller: FOSUserBundle:Security:check }
    requirements:
        _method: POST

# Route de déconnexion du Backoffice
admin_security_logout:
    path:  /admin/logout
    defaults: { _controller: FOSUserBundle:Security:logout }

# Route de mot de passe oublié du Backoffice
admin_resetting_request:
    path:  /admin/request
    defaults: { _controller: FOSUserBundle:Resetting:request }

# Route de mot de passe oublié du Backoffice
admin_resetting_send_email:
    path:  /admin/send-email
    defaults: { _controller: FOSUserBundle:Resetting:sendEmail }

# Route de mot de passe oublié du Backoffice
admin_resetting_check_email:
    path:  /admin/check-email
    defaults: { _controller: FOSUserBundle:Resetting:checkEmail }

# Route de mot de passe oublié du Backoffice
admin_resetting_reset:
    path:  /admin/reset/{token}
    defaults: { _controller: FOSUserBundle:Resetting:reset }
    methods:  [GET, POST]

elfinder:
     resource: "@FMElfinderBundle/Resources/config/routing.yml"

bnbc_upload:
    resource: "@BnbcUploadBundle/Controller/"
    type:     annotation
    prefix:   /upload