<?php

namespace AdminBundle\Repository;

/**
 * CompteFreeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompteFreeRepository extends \Doctrine\ORM\EntityRepository
{
}
