<?php

namespace AdminBundle\Repository;

/**
 * CompteProRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompteProRepository extends \Doctrine\ORM\EntityRepository
{
}
