<?php

namespace AdminBundle\Repository;

/**
 * GalleryVideoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GalleryVideoRepository extends \Doctrine\ORM\EntityRepository
{
}
