<?php

namespace AdminBundle\Repository;

/**
 * ProfilRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfilRepository extends \Doctrine\ORM\EntityRepository
{
	
	
	
	public function findPatient($data)
	{
		$recherche = explode(" ",$data);
		
		$qb = $this->getEntityManager()
        ->createQueryBuilder()
        ->select('p')
        ->from('AdminBundle:Profil', 'p')
				
	  ;
	  foreach ($recherche as $value){
			
			$qb
			->orWhere('p.nom LIKE :data OR p.prenom LIKE :data ')
			->setParameter('data', '%'.$value.'%')
			;
		}
	  
	 

	  return $qb
		->getQuery()
		->getResult()
	  ;
	}
	
	
	
	
	
	
	
	
}
