<?php

namespace AdminBundle\Repository;

/**
 * SubCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubCategoryRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByCategorySlug($slug)
    {
        $qb = $this->createQueryBuilder('s')
            ->select('s, c')
            ->innerJoin('s.category', 'c')
            ->where('c.slug = :slug');

        return $qb
            ->andWhere($qb->expr()->isNull('s.parent'))
            ->addOrderBy('s.parent')
            ->addOrderBy('s.name', 'ASC')
            ->setParameter('slug', $slug)
            ->getQuery()
            ->getResult();
    }

    public function findByCategorySlugWithPosts($slug)
    {
        $qb = $this->createQueryBuilder('s')
            ->select('s, c, p')
            ->innerJoin('s.category', 'c')
            ->innerJoin('s.posts', 'p')
            ->where('c.slug = :slug');

        return $qb
            ->orderBy('s.name', 'ASC')
            ->setParameter('slug', $slug)
            ->getQuery()
            ->getResult();
    }

    public function findByIdWithPosts($id)
    {
        return $this->createQueryBuilder('s')
            ->select('s, p')
            ->innerJoin('s.posts', 'p')
            ->where('s.id = :id')
            /*->orderBy('p', 'ASC')*/
            ->setParameter('id', $id)
            ->getQuery()
            ->getOneOrNullResult();
    }
}
