<?php

namespace GeranceBundle\Repository;

/**
 * FactContratRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FactContratRepository extends \Doctrine\ORM\EntityRepository
{
}
