<?php

namespace GeranceBundle\Repository;

/**
 * ImmobilierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImmobilierRepository extends \Doctrine\ORM\EntityRepository
{
}
