<?php

namespace GeranceBundle\Repository;

/**
 * LocativeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LocativeRepository extends \Doctrine\ORM\EntityRepository
{
}
