<?php

namespace GeranceBundle\Repository;

/**
 * LoyerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LoyerRepository extends \Doctrine\ORM\EntityRepository
{
}
