<?php

namespace GeranceBundle\Repository;

/**
 * MandatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MandatRepository extends \Doctrine\ORM\EntityRepository
{
}
