<?php

namespace GeranceBundle\Repository;

/**
 * OptionPaiementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OptionPaiementRepository extends \Doctrine\ORM\EntityRepository
{
}
