<?php

namespace GeranceBundle\Repository;

/**
 * OptionFactureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OptionFactureRepository extends \Doctrine\ORM\EntityRepository
{
}
