services:
    user.avatar_uploader:
        class: AdminBundle\Uploader\FileUploader
        arguments: ['%avatars_directory%']

    user.listener.user:
        class: UserBundle\User\UserListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ "@annotation_reader" ] ]
            - [ setContainer, [ "@service_container" ] ]
            - [ setContext, [ "@security.token_storage" ] ]